print("Praktikum Programa Komputer ")
print("Exercise 7.27")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
a = [10, 20, 30]
print('a: ', a)
print('min a= ', min(a))
print('max a= ', max(a))