print("Praktikum Programa Komputer ")
print("Exercise 7.9")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
str = 'hello world'
a = str.count('l')
b = str.count('o')
print('jumlah hurus l=', a)
print('jumlah hurus o=', b)
