print("Praktikum Programa Komputer ")
print("Exercise 7.7")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
str = 'hello world'
s = str.capitalize()
print()