print("Praktikum Programa Komputer ")
print("Exercise 7.25")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
a = {'satu': 10, 'dua': 20, 'tiga': 30}
print('a = ', a)
items = a.items()
keys = a.keys()
value = a.values()
print('item: ', items)
print('keys: ', keys)
print('value: ', value)