print("Praktikum Programa Komputer ")
print("Exercise 7.14")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
str = 'Hello world'
str2 = str.upper()
str3 = str.lower()
print(str)
print(str2)
print(str3)