print("Praktikum Programa Komputer ")
print("Exercise 7.12")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
str = 'Hello world'
print('Str : ' + str)
print(' str index o = ', str.index('o'))
print('Str index l = ', str.index('l'))
