#Mulai
print("Soal 2 Tugas 7 Praktikum Programa Komputer ")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
print("Ditanya :")
print("Buatlah 1 program menggunakan fungsi Numerik (Min 3 jenis fungsi numerik)")
print("===========================")
print("")
print("Jawab :")
print("")
print("===========================")
print("")
print("Selamat datang di tempat perhitungan...")
print("")
print("Silahkan masukkan 3 angka berbeda : ")
a = float(input("Angka 1 -> "))
b = float(input("Angka 2 -> "))
c = float(input("Angka 3 -> "))
print("")
print("Angka angka yang anda input adalah : ",a,b,c)
print("")
print("Kami akan menghitung nilai mutlak dari angka yang telah anda input")
print("Mutlak dari Angka 1 adalah ", abs(a))
print("Mutlak dari Angka 2 adalah ", abs(b))
print("Mutlak dari Angka 3 adalah ", abs(c))
import math
print("")
print("Kami akan mengembalikan nilai absolut dari bilangan tersebut, yaitu : ")
print("Nilai absolut angka 1 adalah ", math.fabs(a))
print("Nilai absolut angka 2 adalah ", math.fabs(b))
print("Nilai absolut angka 3 adalah ", math.fabs(c))
print("")
print("Kami akan mencari nilai maksimum dan minimum dari angka tersebut :")
print("")
print("Nilai maksimumnya adalah ", max(a,b,c))
print("Nilai minimumnya adalah ", min(a,b,c))
print("")
print("Kami akan menghitung perpangkatan dan pengakaran dari angka tersebut : ")
d = int(input("Masukkan perpangkatan yang anda inginkan : "))
e = int(input("Masukkan pengakaran yang anda inginkan : "))
print("")
print("Nilai dari perpangkatan ketiga angka tersebut adalah : ")
print("Angka 1 : ", a**d)
print("Angka 2 : ", b**d)
print("Angka 3 : ", c**d)
print("")
print("Nilai dari pengakaran ketiga angka tersebut adalah : ")
print("Angka 1 : ", a**1/e)
print("Angka 2 : ", b**1/e)
print("Angka 3 : ", c**1/e)
print("")
print("Ini adalah akhir dari pemrograman")
input("klik enter untuk kembali")
print("Mohon maaf apabila terdapat kesalahan")
#Selesai




