print("Praktikum Programa Komputer ")
print("Exercise 7.13")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
str = 'Hello world'
print('str: ' + str)
print('str replace Hello= ', str.replace('Hello', 'Hai'))
print('str replace world= ', str.replace('world', 'Dunia'))
