print("Praktikum Programa Komputer ")
print("Exercise 7.22")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
a = {'satu': 10, 'dua': 20, 'tiga': 30}
b = {'satu': 10, 'dua': 20}
print('a = ', a)
print('b = ', b)
print('nilai len a = ', len(a))
print('nilai len b = ', len(b))