print("Praktikum Programa Komputer ")
print("Exercise 7.35")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
a = [10, 40, 30, 10, 70, 40]
print('a awal: ', a)
a.sort()
print('a sesudah diurutkan: ', a)