#Mulai
print("Soal 1 Tugas 7 Praktikum Programa Komputer ")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
print("Ditanya :")
print("Buatlah 1 program menggunakan fungsi string (Min 3 jenisfungsi string)")
print("===========================")
print("")
print("Jawab :")
print("")
print("===========================")
print("")
x = str(input("Masukkan kata/kalimat yang anda inginkan : "))
print("")
print("Kata/kalimat yang anda masukkan akan kami Capitalize, menjadi : ")
print("")
a = x.capitalize()
print(a)
print("")
print("Kata/kalimat yang anda masukkan akan kami Center, menjadi : ")
str = x
b = str.center(50,'=')
print(b)
print("")
c = input("Masukkan huruf yang anda ingin hitung jumlahnya pada kalimat tersebut : ")
str = x
d = str.count(c)
print("Jumlah huruf", c, "adalah : ", d)
print("")
e = input("Masukkan kata yang ingin anda replace : ")
print("")
f = input("Masukkan kata pengganti : ")
print("")
print("kata yang ingin anda replace adalah : ", e,"menjadi kata : ", f)
print("")
str = x
print("Hasil dari kata baru adalah : ", str.replace(e,f))
print("")
print("Ini adalah akhir dari pemrograman")
print("")
input("Klik enter untuk kembali.....")
print("Note : mohon maaf apabila terdapat kesalahan")
#Selesai




