print("Praktikum Programa Komputer ")
print("Exercise 7.21")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
import random
a = [23, 45, 98, 36]
print('a = ', a)
print('random 1')
print('choice = ', random.choice(a))
print('random 2')
print('choice = ', random.choice(a))
print('random 3')
print('choice = ', random.choice(a))