print("Praktikum Programa Komputer ")
print("Exercise 7.34")
print("")
print("===========================")
print("Nama : Ivanindra Rizky P")
print("NIM : I0320054")
print("")
print("===========================")
print("")
a = [10, 40, 30, 10, 70, 30]
print('a awal: ', a)
a.reverse()
print('a sesudah di reverse: ', a)